### PR TITLE
Fixes #16

### LINKED ISSUE #16: Tick action fails
When trying to invoke ticktok.tick() I get the following exception 

> was BEGIN_ARRAY at line 1 column 2 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:922)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:836)
        at com.google.gson.Gson.fromJson(Gson.java:808)
        at io.ticktok.client.server.rest.RestClockActions.clockFrom(RestClockActions.java:50)
        at io.ticktok.client.server.rest.RestClockActions.getClockBy(RestClockActions.java:42)
        at io.ticktok.client.server.rest.RestClockActions.tick(RestClockActions.java:28)
        at io.ticktok.client.Ticktok.tick(Ticktok.java:29)
        at io.ticktok.sanity.SanityCheck.main(SanityCheck.java:22)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
        ... 9 more

### PR DESCRIPTION
**Pull request by rockem**

### CODE REVIEW

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java [hunk 1]
```diff
@@ -38,8 +42,14 @@ private Clock getClockBy(ClockRequest clockRequest) throws IOException {
         final HttpGet httpGet = new HttpGet(urlResolver.queryParam("name", clockRequest.getName()).queryParam("schedule", clockRequest.getSchedule()).resolve());
         HttpResponse httpResponse = httpClient.execute(httpGet);
         String entity = extractEntityFrom(httpResponse);
-        new RestResponseValidator(httpResponse).validate(200, new ClockNotFoundException(entity));
-        return clockFrom(entity);
+        final List<Clock> clocks = new Gson().fromJson(entity, new TypeToken<List<Clock>>() {}.getType());
+        if(clocks.isEmpty()) {
```
Comment (amaziagur) [inline src/main/java/io/ticktok/client/server/rest/RestClockActions.java]: extract to method

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java [hunk 2]
```diff
@@ -38,8 +42,14 @@ private Clock getClockBy(ClockRequest clockRequest) throws IOException {
         final HttpGet httpGet = new HttpGet(urlResolver.queryParam("name", clockRequest.getName()).queryParam("schedule", clockRequest.getSchedule()).resolve());
         HttpResponse httpResponse = httpClient.execute(httpGet);
         String entity = extractEntityFrom(httpResponse);
-        new RestResponseValidator(httpResponse).validate(200, new ClockNotFoundException(entity));
-        return clockFrom(entity);
+        final List<Clock> clocks = new Gson().fromJson(entity, new TypeToken<List<Clock>>() {}.getType());
```
Comment (amaziagur) [inline src/main/java/io/ticktok/client/server/rest/RestClockActions.java:48]: are there other types of clocks ? of is there only one type == class? if there is im not sure you need to use typeToken

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java [hunk 3]
```diff
@@ -38,8 +42,14 @@ private Clock getClockBy(ClockRequest clockRequest) throws IOException {
...
+        if(clocks.isEmpty()) {
+            throw new ClockNotFoundException(format(
+                    "Clock named: %s, schedule: %s isn't currently configured",
+                    clockRequest.getName(),
+                    clockRequest.getSchedule()));
+        }
+        return clocks.get(0);
```
Comment (amaziagur) [inline src/main/java/io/ticktok/client/server/rest/RestClockActions.java:53]: i would extract the 0 to a const with meaningful name

**Review by amaziagur — CHANGES_REQUESTED** [review]

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 2 above)
Comment (rockem) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:48]: You always need a typetoken for lists

Comment (amaziagur) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:48]: you are right....

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 1 above)
Comment (rockem) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java]: done

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java [hunk 4]
```diff
@@ -12,6 +13,9 @@
 import org.apache.http.util.EntityUtils;
 
 import java.io.IOException;
+import java.util.List;
+
```
Comment (amaziagur) [inline src/main/java/io/ticktok/client/server/rest/RestClockActions.java:17]: drop space

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 2 above)
Comment (amaziagur) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:48]: since you have a `return` statement here, i would refactor name to something like this:
`return topClockFrom` or `return firstClockFrom`

Comment (amaziagur) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:48]: in params i would pass the name and the schedule as is and not the whole `clockRequest` object, since you only need it for exception...

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 3 above)
Comment (amaziagur) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:53]: some reaction to this offer :)...

**Review by amaziagur — CHANGES_REQUESTED** [review]

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 3 above)
Comment (rockem) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:53]: I don't think 0 will confuse a programmer here, and the function name clearly state the intent

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 2 above)
Comment (rockem) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:48]: done

File: src/main/java/io/ticktok/client/server/rest/RestClockActions.java (hunk 4 above)
Comment (rockem) [reply src/main/java/io/ticktok/client/server/rest/RestClockActions.java:17]: This is the standard formatting I didn't add it

**Review by amaziagur — APPROVED** [review]
